section_contact-us
PushEaxVK/watch-charm pull request #2
Opened 2024-11-16 17:45 UTC by Myrosya-fsd

Вітаю, надсилаю секцію contact-us

2024-11-16 18:26 UTC, PushEaxVK commented on src/partials/contact-us.html
> +         media="(min-width: 320px)"
заміни `media="(min-width: 320px)"` на `media="(max-width: 767px)"`

2024-11-16 18:35 UTC, PushEaxVK reviewed
Перенести зображення у папку src/img/contact-us

2024-11-16 18:46 UTC, PushEaxVK commented on src/css/contact-us.css
> +@media screen and (min-width: 320px) {
не використовуй `@media screen and (min-width: 320px)` такий медіа запит. В нас підхід Mobile First. Все що для мобілки робиться без медізапиту, а безпосередньо у коді. А вотім вже медіазапитами адаптуємо мобільну версію для планшета та десктопа.

2024-11-16 18:49 UTC, PushEaxVK reviewed
не використовуй @media screen and (min-width: 320px)

2024-11-16 19:03 UTC, PushEaxVK commented on src/css/contact-us.css
> +  margin-bottom: 20px;
для планшета треба: `margin-bottom: 40px;`

2024-11-16 19:08 UTC, PushEaxVK commented on src/css/contact-us.css
> +  background-color: #ffffff;
background-color має бути #fbfbfb

2024-11-16 19:12 UTC, PushEaxVK commented on src/css/contact-us.css
> +  padding-top: 30px;
Ми не використовуємо вертикальні падінги для відступів між секціями. Тільки марджини

2024-11-16 19:14 UTC, PushEaxVK reviewed
Ще трохи review

2024-11-16 20:01 UTC, PushEaxVK commented on src/css/contact-us.css
> +@media (min-width: 320px) {
Видалити цю стрічку і закриваючу дужку. Не використовуй` @media screen and (min-width: 320px)` такий медіа запит. В нас підхід Mobile First. Все що для мобілки робиться без медізапиту, а безпосередньо у коді. А вотім вже медіазапитами адаптуємо мобільну версію для планшета та десктопа.

2024-11-16 20:02 UTC, PushEaxVK commented on src/css/contact-us.css
> +}
Ось цю закриваючу дужку теж видалити

2024-11-16 20:02 UTC, PushEaxVK commented on src/css/contact-us.css
> +    padding-top: 30px;
Замінити на margin

2024-11-16 20:03 UTC, PushEaxVK commented on src/css/contact-us.css
> +    padding-bottom: 30px;
І тут замінити padding на margin

2024-11-16 20:11 UTC, PushEaxVK commented on src/css/contact-us.css
> +
Додати border-radius для зображення
`css
.card {
  border-radius: 30px;
}
`

2024-11-16 22:21 UTC, PushEaxVK commented on src/css/contact-us.css
> +
Додати border-radius для зображення

```css
.card {
  border-radius: 30px;
}
```

2024-11-16 22:22 UTC, PushEaxVK commented on src/css/contact-us.css
> +    border-radius: 30px;
Видалити звідси border-radius

2024-11-16 22:22 UTC, PushEaxVK commented on src/css/contact-us.css
> +    background-color: url(/img/contact-us/Rectangle-dis-1x.jpg);
цей background-color теж видалити

2024-11-16 22:24 UTC, PushEaxVK commented on src/css/contact-us.css
> +
Додати border-radius для зображення

```css
.card {
  border-radius: 50px;
}
```

2024-11-16 22:24 UTC, PushEaxVK commented on src/css/contact-us.css
> +    border-radius: 50px;
Видалити border-radius звідси

2024-11-16 22:26 UTC, PushEaxVK commented on src/partials/contact-us.html
> +          class="responsive-image"
Видалити дублюючий атрибут class

2024-11-16 22:30 UTC, PushEaxVK commented on src/css/contact-us.css
> +  border-radius: 30px;
Видалити звідси border-radius та додати його в клас .card

2024-11-16 22:37 UTC, PushEaxVK requested changes
Ось ще кілька зауважень

2024-11-16 22:47 UTC, PushEaxVK commented on src/css/contact-us.css
> +  background-color: url(/img/contact-us/Rectangle-dis-1x.jpg);
Видалити background-color

2024-11-16 22:50 UTC, PushEaxVK reviewed
І знов review

2024-11-17 16:35 UTC, PushEaxVK commented on src/css/contact-us.css
> +  margin: 0 auto;
Перемістити `margin: 0 auto;` вище ніж `margin-top: 30px;` та `margin-bottom: 30px;` або замість `margin: 0 auto;` написати `margin-left: auto;` та `margin-right: auto`

2024-11-18 22:09 UTC, PushEaxVK submitted a review, later dismissed

2024-11-18 22:11 UTC, PushEaxVK commented on src/css/contact-us.css
> +  width: 1;
```css
width: 100%;
```

2024-11-18 22:19 UTC, PushEaxVK commented on src/css/contact-us.css
> +    min-height: 556px;
Тут вже можна поставити height замість min-height бо резиновість має бути тільки для мобільної версії.
```css
height: 556px;
```

2024-11-18 22:22 UTC, PushEaxVK reviewed
Ось кілька виправлень

2024-11-19 00:27 UTC, PushEaxVK commented on src/partials/contact-us.html
>  <section class="contact">
додати `id="contact-us"`

2024-11-19 13:53 UTC, Myrosya-fsd commented on src/css/contact-us.css
> +  width: 1;
але я виправила на 100% і я тобі після виправлення залила зі змінами, нічого не розумію, та й впринципі не розумію яким чином першого разу зі 100% полулилася 1

2024-11-20 02:11 UTC, PushEaxVK commented on src/partials/contact-us.html
> +<section id="made" class="contact">
Зміни id на contact-us: `id="contact-us"`

2024-11-20 02:14 UTC, PushEaxVK commented on src/partials/contact-us.html
> +            pattern="^\+\d{3}-\d{2}-\d{3}-\d{2}-\d{2}$ (+380-XX-XXX-XX-XX)"
Видали з паттерна  (+380-XX-XXX-XX-XX). Паттерн це тільки `^\+\d{3}-\d{2}-\d{3}-\d{2}-\d{2}$`

2024-11-20 12:02 UTC, PushEaxVK reviewed
Не працює transition на кнопці

2024-11-20 12:02 UTC, PushEaxVK commented on src/css/contact-us.css
> +  transition: border-color 250ms cubic-bezier(0.4, 0, 0.2, 1);
Заміни border-color на background-color

2024-11-20 12:18 UTC, PushEaxVK approved these changes
Готово!

2024-11-20 12:18 UTC, merged